name: Nightly Data Pipeline

on:
  schedule:
    - cron: '0 5 * * *' # Runs every day at 5 AM UTC
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  build-and-embed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 openai psycopg2-binary python-dotenv sentence-transformers gspread google-api-python-client google-auth-httplib2 oauth2client pandas

      - name: Authenticate with Google
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}'

      - name: Run Data Pipeline
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
          GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
          GOOGLE_DRIVE_FOLDER_ID: ${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}
        run: python pipeline.py